project:
  type: book

book:
  title: "Apuntes sobre Modelización de Computación Predictiva"
  author: "Carlos G"
  date: "3/7/2026"
  chapters:
    - index.qmd
    - t1-intro-R.qmd
    - t1-tidyverse.qmd
    - t1-ggplot2.qmd
    - t2-sistemas-ecuaciones.qmd
    - t3-autovalores.qmd
    - t5-PCA.qmd
    - t6-redes-sociales.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    cover-image: cover.png
    documentclass: scrreprt



