project:
  type: book

book:
  title: "Apuntes sobre Modelización de Computación Predictiva"
  author: "Carlos G"
  date: "3/7/2026"
  chapters:
    - index.qmd
    - part: "Capítulos"
      chapters:
        - chapters/t1-intro-R.qmd
        - chapters/t1-tidyverse.qmd
        - chapters/t1-ggplot2.qmd
        - chapters/t2-sistemas-ecuaciones.qmd
        - chapters/t3-autovalores.qmd
        - chapters/t5-PCA.qmd
        - chapters/t6-redes-sociales.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    cover-image: cover.png
    documentclass: scrreprt



